USER: melanmeg
TARGET_BRANCH: main

# kubernetes v1.30
INSTALL_KUBE_VERSION: 1.30.4-1.1
KUBE_VERSION: 1.30.4
CRI_SOCKET_PATH: /var/run/containerd/containerd.sock

# kubernetes v1.31
# INSTALL_KUBE_VERSION: 1.31.0-1.1
# KUBE_VERSION: 1.31.0
# Containerd V2
# CRI_SOCKET_PATH: /run/containerd/containerd.sock

KUBE_API_SERVER_VIP: 192.168.11.130

VM_HOSTNAME_WK_1: test-k8s-wk-1
VM_HOSTNAME_WK_2: test-k8s-wk-2
VM_HOSTNAME_WK_3: test-k8s-wk-3
